"""add low stock to products

Revision ID: 4d11c1d43e29
Revises: ea9fcfcfed5e
Create Date: 2026-09-29 14:27:05.717530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d11c1d43e29'
down_revision: Union[str, None] = 'ea9fcfcfed5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('low_stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'low_stock')
    # ### end Alembic commands ###
