"""add low stock to products

Revision ID: a1b25283bc14
Revises: 4d11c1d43e29
Create Date: 2026-09-29 15:03:31.804320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b25283bc14'
down_revision: Union[str, None] = '4d11c1d43e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.drop_column('sale_items', 'unit_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_column('sale_items', 'price')
    # ### end Alembic commands ###
